# Generated by Django 4.2.28 on 2026-07-13 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_learning_goal_user_preferred_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_id',
            field=models.CharField(blank=True, default='a1', max_length=10),
        ),
    ]
