# Generated by Django 4.2.30 on 2026-07-18 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_institutional_registration_and_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('institutional_admin', 'Institutional Admin'), ('mentor', 'Mentor')], max_length=50, unique=True),
        ),
    ]
