# Generated by Django 4.2.30 on 2026-06-25 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_category_show_type'),
        ('ranks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Fill only for Category-Wise ranks', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ranks', to='courses.category'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='color',
            field=models.CharField(default='#CD7F32', help_text='Hex color, e.g. #CD7F32 for Bronze', max_length=7),
        ),
        migrations.AlterField(
            model_name='rank',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='overall_timer_seconds',
            field=models.PositiveIntegerField(default=300, help_text='Total seconds for the entire test. Used when has_overall_timer=True.'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='pass_percentage',
            field=models.PositiveIntegerField(default=70, help_text='Min % to pass each lesson in this rank'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='question_timer_seconds',
            field=models.PositiveIntegerField(default=30, help_text='Seconds per question. 0 = no limit.'),
        ),
        migrations.AlterField(
            model_name='testlog',
            name='ended_by_timer',
            field=models.BooleanField(default=False, help_text='True if the overall timer expired before user finished'),
        ),
        migrations.AlterField(
            model_name='testlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='testlog',
            name='question_detail',
            field=models.JSONField(default=list, help_text='[{target, chosen, correct, result: correct|wrong|timeout}]'),
        ),
        migrations.AlterField(
            model_name='userrankprogress',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userrankprogress',
            name='is_current',
            field=models.BooleanField(default=False, help_text="True if this is the user's active rank"),
        ),
        migrations.AlterField(
            model_name='xpconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='xpconfig',
            name='study_xp',
            field=models.PositiveIntegerField(default=10, help_text='XP awarded for completing the Study mode of this lesson'),
        ),
        migrations.AlterField(
            model_name='xpconfig',
            name='test_xp',
            field=models.PositiveIntegerField(default=50, help_text='XP awarded for passing the Test of this lesson'),
        ),
    ]
