# Generated by Django 4.2.30 on 2026-07-13 04:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ranks', '0002_alter_rank_category_alter_rank_color_alter_rank_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRevisionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timer_minutes', models.PositiveIntegerField(default=10)),
                ('per_question_xp', models.PositiveIntegerField(default=5)),
                ('overall_completion_xp', models.PositiveIntegerField(default=10)),
                ('streak_count', models.PositiveIntegerField(default=1)),
                ('daily_limit', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_revision_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Revision Config',
                'verbose_name_plural': 'Daily Revision Configs',
            },
        ),
        migrations.CreateModel(
            name='DailyRevisionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.PositiveIntegerField(default=0)),
                ('correct', models.PositiveIntegerField(default=0)),
                ('wrong', models.PositiveIntegerField(default=0)),
                ('timed_out', models.PositiveIntegerField(default=0)),
                ('score_pct', models.FloatField(default=0.0)),
                ('xp_gained', models.PositiveIntegerField(default=0)),
                ('streak_gained', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_revision_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
