# Generated by Django 4.2.28 on 2026-07-12 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ranks', '0002_alter_rank_category_alter_rank_color_alter_rank_id_and_more'),
        ('courses', '0002_category_show_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankquestion',
            name='wrong_4',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='lesson',
            name='rank',
            field=models.ForeignKey(blank=True, help_text='Leave blank to show this lesson to all ranks', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='ranks.rank'),
        ),
        migrations.AddField(
            model_name='studyitem',
            name='wrong_4',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
