# Generated by Django 4.2.30 on 2026-07-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_bankquestion_wrong_4_lesson_rank_studyitem_wrong_4'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyitem',
            name='exp6',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
