# Generated by Django 4.2.28 on 2026-07-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_studyitem_exp6'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='test_questions_count',
            field=models.PositiveIntegerField(default=40, help_text='How many questions to draw for each take-test from all active banks'),
        ),
    ]
