# Generated by Django 4.2.28 on 2026-07-12 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_lesson_test_questions_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='has_overall_timer',
            field=models.BooleanField(default=False, help_text='Enable an overall test timer for lessons in this category'),
        ),
        migrations.AddField(
            model_name='category',
            name='overall_timer_seconds',
            field=models.PositiveIntegerField(default=300, help_text='Default overall test duration for this category'),
        ),
        migrations.AddField(
            model_name='category',
            name='question_timer_seconds',
            field=models.PositiveIntegerField(default=30, help_text='Default seconds per question for lessons in this category'),
        ),
    ]
