# Generated by Django 4.2.30 on 2026-07-18 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_category_has_overall_timer_and_more'),
        ('roleplay', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roleplaystory',
            name='jlpt_level',
        ),
        migrations.AddField(
            model_name='roleplaystory',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roleplay_stories', to='courses.exam'),
        ),
    ]
