# Generated by Django 4.2.30 on 2026-07-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roleplay', '0002_remove_roleplaystory_jlpt_level_roleplaystory_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='roleplayroom',
            name='current_dialogue_index',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
